#!/bin/bash

pkg-config --exists cairo-xcb ||
{
    echo -e "\033[31m######################################################\033[0m"
    echo -e "\033[31m#\033[0m \033[1mCairo doit avoir le support xcb !\033[0m              \033[31m#\033[0m"
    echo -e "\033[31m#\033[0m \033[1mInstallez xorg-xcb-util, et recompilez cairo.\033[0m \033[31m#\033[0m"
    echo -e "\033[31m######################################################\033[0m"
    echo -e "\033[36;1mSleeping for 10 seconds before proceeding.\033[0m"
    sleep 10
    exit 1
}
